[browser]
gatherUsageStats = false
serverAddress = "localhost"   # fuerza que el navegador apunte a localhost

[server]
address = "localhost"         # escucha solo en localhost (no red)
port = 8501                   # cambia si lo necesitas
headless = false              # true = no intenta abrir navegador
fileWatcherType = "auto"      # o "poll" si hay restricciones de fs
